//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhalidPetroleum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public long UserID { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public string ArrivalTime { get; set; }
        public string DepartureTime { get; set; }
        public bool AttendanceStatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
