//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhalidPetroleum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckList_Question
    {
        public long CheckListID { get; set; }
        public long QuestionID { get; set; }
        public bool Status { get; set; }
        public long CheckListQuestionID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual DailyCheckList DailyCheckList { get; set; }
    }
}
