//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhalidPetroleum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReportSale
    {
        public long DailyReportSalesID { get; set; }
        public long DailyReportID { get; set; }
        public long DeliveryNo { get; set; }
        public double Quantity { get; set; }
        public long SiteID { get; set; }
        public string SaleReceiptImage { get; set; }
    
        public virtual UnloadSite UnloadSite { get; set; }
        public virtual DailyReport DailyReport { get; set; }
    }
}
