//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhalidPetroleum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depot
    {
        public Depot()
        {
            this.DailyReports = new HashSet<DailyReport>();
        }
    
        public long DepotCode { get; set; }
        public string DepotName { get; set; }
        public string DepotLocation { get; set; }
        public Nullable<bool> DepotStatus { get; set; }
    
        public virtual ICollection<DailyReport> DailyReports { get; set; }
    }
}
