//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhalidPetroleum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.CheckList_Question = new HashSet<CheckList_Question>();
        }
    
        public long QuestionID { get; set; }
        public string QuestionStatement { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<CheckList_Question> CheckList_Question { get; set; }
    }
}
