//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhalidPetroleum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long TaskId { get; set; }
        public string TaskName { get; set; }
        public string Details { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EstimatedDate { get; set; }
        public long TaskOwner { get; set; }
        public Nullable<long> AssignedTo { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<int> TaskType { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<long> DailyChecklistId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    }
}
