//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhalidPetroleum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnloadSite
    {
        public UnloadSite()
        {
            this.DailyReportSales = new HashSet<DailyReportSale>();
        }
    
        public long SiteID { get; set; }
        public string SiteName { get; set; }
        public string SiteLocation { get; set; }
        public double ChargingRate { get; set; }
        public int ParentCompany { get; set; }
        public bool SiteStatus { get; set; }
    
        public virtual ICollection<DailyReportSale> DailyReportSales { get; set; }
    }
}
