//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhalidPetroleum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Attendances = new HashSet<Attendance>();
            this.DailyReports = new HashSet<DailyReport>();
        }
    
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserCNIC { get; set; }
        public Nullable<System.DateTime> UserDOB { get; set; }
        public Nullable<bool> UserGender { get; set; }
        public string UserType { get; set; }
        public string UserAddress { get; set; }
        public bool UserStatus { get; set; }
        public string UserPassword { get; set; }
        public string Userusername { get; set; }
        public Nullable<long> RoleID { get; set; }
        public Nullable<long> SupervisorGroupId { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<DailyReport> DailyReports { get; set; }
        public virtual Role Role { get; set; }
    }
}
